plugins:
  - eslint-plugin-vue

extends:
  - ../../../.eslintrc.yaml
  - plugin:vue/vue3-recommended

env:
  browser: true

rules:
  vue/attributes-order: [0]
  vue/html-closing-bracket-spacing: [2, {startTag: never, endTag: never, selfClosingTag: never}]
  vue/max-attributes-per-line: [0]
